# it is not really python, but there is no R support on Travis CI yet
language: python

sudo: false

addons:
  apt:
    packages:
      - python-virtualenv
      - gfortran

# environment variables
env:
  - PYTHONPATH=~/vtk-precise64/lib/python2.7/site-packages:~/vtk-precise64/lib LD_LIBRARY_PATH=~/vtk-precise64/lib

before_install:
  - pushd "${HOME}"
  - curl "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGO_VERSION}.tgz" | gunzip -c | tar x
  - cd mongodb-*/bin && export PATH="${PWD}:${PATH}"
  - popd
  - mkdir /tmp/db
  - mongod --dbpath=/tmp/db >/dev/null 2>/dev/null &
  - mongod --version
  - pushd "${HOME}"
  - curl "http://www.cmake.org/files/v3.2/cmake-3.2.2-Linux-x86_64.tar.gz" | gunzip -c | tar x
  - cd cmake-*/bin && export PATH="${PWD}:${PATH}"
  - popd
  - cmake --version
  # download VTK
  - wget http://midas3.kitware.com/midas/download/bitstream/366970/vtk-precise64-118242.tar.gz -O vtk-precise64.tar.gz
  - tar xzvf vtk-precise64.tar.gz -C ~
  # install R
  - eval "$(curl https://data.kitware.com/api/v1/file/55735da88d777f649a9ba181/download | /bin/bash)"
  - eval "$(travis-install 5575e0d88d777f649a9ba197)"
  - R --version
  - R -e '.libPaths(); sessionInfo()'

# install dependencies
install:
  # install Python packages
  - pip install -U -e .[pandas]             # This installs all standard deps + pandas extras
  - pip install -U -r requirements-dev.txt  # This installs development packages

# run tests
script:
  - mkdir _build
  - cd _build
  - cmake -D PYTHON_COVERAGE:BOOL=ON ..
  - ctest -VV -S ../cmake/travis_continuous.cmake || true
  - if [ -f test_failed ] ; then false ; fi
  - cd ..

after_success:
  - coveralls
